### ISSUE TITLE
Binary file metadata not found

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/lib-eda-subsetting#40]
Caching log lines:
```
ESC[mESC[32m2023-12-06 10:29:30.466 [rid:     ] INFO  MetadataCache:113 - Checking which studies are out of date in cache.
ESC[mESC[32m2023-12-06 10:29:30.481 [rid:     ] INFO  MetadataCache:119 - Removing the following out of date or missing studies from cache:
```

## Fix
Clear cache

## Stack Trace

```
ESC[mESC[33m2023-12-06 10:32:40.508 [rid:     ] WARN  ErrorMapper:70 - Caught Exception:
ESC[m java.lang.IllegalStateException: No metadata file was found to parse binary properties from for variable PATO_0000047
        at org.veupathdb.service.eda.ss.model.variable.StringVariable.getStringConverter(StringVariable.java:45) ~[service.jar:3.9.0]
        at org.veupathdb.service.eda.ss.model.reducer.BinaryValuesStreamer.streamIdValueBinaryPairs(BinaryValuesStreamer.java:100) ~[service.jar:3.9.0]
        at org.veupathdb.service.eda.ss.model.db.FilteredResultFactory.produceTabularSubsetFromFile(FilteredResultFactory.java:186) ~[service.jar:3.9.0]
        at org.veupathdb.service.eda.ss.service.StudiesService.lambda$handleTabularRequest$7(StudiesService.java:291) ~[service.jar:3.9.0]
        at org.veupathdb.service.eda.generated.model.EntityTabularPostResponseStream.write(EntityTabularPostResponseStream.java:21) ~[service.jar:3.9.0]
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55) ~[service.jar:3.9.0]
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37) ~[service.jar:3.9.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242) ~[service.jar:3.9.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227) ~[service.jar:3.9.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.9.0]
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85) ~[service.jar:3.9.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.9.0]
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61) ~[service.jar:3.9.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.9.0]
        at org.veupathdb.lib.container.jaxrs.server.middleware.PrometheusFilter.aroundWriteTo(PrometheusFilter.java:135) ~[service.jar:3.9.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.9.0]
        at org.veupathdb.lib.container.jaxrs.server.middleware.RequestIdFilter.aroundWriteTo(RequestIdFilter.java:70) ~[service.jar:3.9.0]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139) ~[service.jar:3.9.0]
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116) ~[service.jar:3.9.0]
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:677) [service.jar:3.9.0]
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:385) [service.jar:3.9.0]
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:375) [service.jar:3.9.0]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:264) [service.jar:3.9.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [service.jar:3.9.0]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [service.jar:3.9.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [service.jar:3.9.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [service.jar:3.9.0]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [service.jar:3.9.0]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [service.jar:3.9.0]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240) [service.jar:3.9.0]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697) [service.jar:3.9.0]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367) [service.jar:3.9.0]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) [service.jar:3.9.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) [service.jar:3.9.0]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) [service.jar:3.9.0]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by dmgaldi** [comment]
I think the issue is that we're not refreshing the binary metadata if the files change out from under the service.
